# Generated by Django 3.1.6 on 2021-06-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20210626_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=50)),
                ('blue_division', models.BooleanField(default=False)),
                ('green_division', models.BooleanField(default=False)),
                ('red_division', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserOnlineJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acm.judgename')),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.link')),
            ],
        ),
    ]
