# Generated by Django 3.1.6 on 2021-06-27 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acm', '0002_auto_20210627_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemSolving',
            new_name='ProblemDetails',
        ),
    ]
