# Generated by Django 3.1.6 on 2021-06-28 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acm', '0003_auto_20210627_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersolveproblem',
            name='semester',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StudentDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red')], max_length=1)),
                ('semester', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
