# Generated by Django 3.1.6 on 2021-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0004_auto_20210628_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
    ]
