# Generated by Django 3.1.6 on 2021-07-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0005_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgename',
            name='blue_division',
        ),
        migrations.RemoveField(
            model_name='judgename',
            name='green_division',
        ),
        migrations.RemoveField(
            model_name='judgename',
            name='red_division',
        ),
    ]
