# Generated by Django 3.1.6 on 2021-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedIn',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
