# Generated by Django 3.1.6 on 2021-06-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210622_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='club_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.clubposition'),
        ),
    ]
