# Generated by Django 3.1.6 on 2021-06-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210625_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubposition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='club_role',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.clubposition'),
        ),
    ]
